{% set name = "caf.toolkit" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caf.toolkit-{{ version }}.tar.gz
  sha256: 85a3096fd147b06ca8c50d1dc939d1ce9297635d7ce8b2302c880735c7d652ba


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0.0
    - versioningit
    - pip
  run:
    - python >=3.9
    - numpy >=1.19.0
    - pandas >=1.4.0
    - tqdm >=4.50.2
    - sparse >=0.13.0, <0.15.0  # Error with conda recognising latest version number 15/01/24
    - pydantic >=2.5.0
    - strictyaml >=1.6
    - psutil >=5.9.0

test:
  imports:
    - caf.toolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.toolkit
  summary: A toolkit of transport planning and appraisal functionalities
  dev_url: https://github.com/Transport-for-the-North/caf.toolkit
  license: TfN-License
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenTaylor-TfN
    - isaac-tfn
