{% set name = "caf.toolkit" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/caf.toolkit-{{ version }}.tar.gz
  sha256: ec18a2da8511c4f8bd6090bb207bf237a295d8de35e2138b94e3251dff03395c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
    - versioneer-518
  run:
    - python >=3.9
    - numpy >=1.19.0
    - pandas >=1.4.0
    - tqdm >=4.50.2
    - openpyxl >=3.0.5
    - sparse >=0.13.0
    - numba >=0.56.4

test:
  imports:
    - caf.toolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Transport-for-the-North/caf.toolkit
  summary: A toolkit of transport planning and appraisal functionalities
  dev_url: https://github.com/Transport-for-the-North/caf.toolkit
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BenTaylor-TfN
